-- Run once in Supabase SQL Editor (same project as favorites / recipe_history).

create table if not exists custom_recipes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  subtitle text default '',
  time text default '',
  cost text default '',
  level text default 'Beginner',
  tag text default 'Quick Meal',
  image text default '🍽️',
  ingredients jsonb not null default '[]',
  steps jsonb not null default '[]',
  why text default '',
  created_at timestamptz default now()
);

alter table custom_recipes enable row level security;

create policy "Users manage own custom recipes"
  on custom_recipes for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
