-- Run once in Supabase SQL Editor (same project as favorites / custom_recipes).
-- Tracks each browse/open event per user so preferences can be analyzed and synced.

create table if not exists recipe_history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  recipe_id bigint not null,
  action_type text not null default 'browsed',
  created_at timestamptz default now()
);

-- Speeds up "this user's most recent history" reads.
create index if not exists recipe_history_user_created_idx
  on recipe_history (user_id, created_at desc);

alter table recipe_history enable row level security;

create policy "Users manage own history"
  on recipe_history for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
